apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "my-python-api.fullname" . }}-db-creds"
  labels:
    {{- include "my-python-api.labels" . | nindent 4 }}
stringData:
    PG_USERNAME: {{ .Values.db.username }}
    PG_PASSWORD: {{ .Values.db.password }}
    DB_HOST: {{ .Values.db.host }}
    DB_NAME: {{ .Values.db.name }}
