---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-python-api-local
  namespace: default
spec:
  gateways:
  - default/default
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /my-python-api/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ include "my-python-api.fullname" . }}
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-python-api
  namespace: default
spec:
  gateways:
  - default/default
  hosts:
  - "local.leehughs.com"
  http:
  - name: Public Ingress
    route:
    - destination:
        host: {{ include "my-python-api.fullname" . }}
        port:
          number: 80